#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
app_swagger_ui:
    path: /documentation
    methods: GET
    defaults: { _controller: api_platform.swagger.action.ui, area: default }